apiVersion: fn.kpt.dev/v1alpha1
kind: Replacements
metadata:
  name: configure-rolebinding-group
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: ConfigMap
      name: rolebinding-group
      fieldPath: data.name
    targets:
      - select:
          kind: RoleBinding
          name: appadmin
        fieldPaths:
          - subjects.[kind=Group].name
        options:
          create: true
