apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: generate-rolebinding-group.yaml
  annotations:
    config.kubernetes.io/local-config: "true"
source: |-
  load("krmfn.star", "krmfn")
  
  def generate_group(resources, role):
    group = ""
    value_store = {}
    for r in resources:
      if krmfn.match_gvkn(r, "v1", "ConfigMap", "gcloud-config.kpt.dev"):
        project = r["data"]["projectID"]
        domain = r["data"]["domain"]
      if krmfn.match_gvkn(r, "v1", "ConfigMap", "kptfile.kpt.dev"):
        namespace = r["data"]["name"]
      if krmfn.match_gvkn(r, "v1", "ConfigMap", "value-store"):
        value_store = r
    group = project + "-" + namespace + "-" + role + "@" + domain
    value_store["data"]["group"] = group

  generate_group(ctx.resource_list["items"], "app-admin")
