apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-rolebinding-group
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: ConfigMap
      name: value-store
      fieldPath: data.group
    targets:
      - select:
          kind: RoleBinding
          name: app-admin
        fieldPaths:
          - subjects.[kind=Group].name
        options:
          create: true
