apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appadmin
  namespace: myns
subjects:
- kind: Group
  name: example-admin@example.com
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: sa
roleRef:
  kind: ClusterRole
  name: appadmin
  apiGroup: rbac.authorization.k8s.io
